version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/E2E-CRUD
    ports:
      - 8080:8080
    image: app:node-db
    container_name: node_db_container
    command: npm start